# netlify.toml

[build]
  # O comando de build da UI pode ser movido para cรก
  command = "cp firebase-config.template.js firebase-config.js && sed -i '...' && sed -i '...'" # (comando completo)
  publish = "."

[functions]
  directory = "netlify/functions" 